name: ipfs

services:
  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "4001:4001"  # swarm listening port
      - "5001:5001"  # API port
      - "8080:8080"  # Gateway port
    environment:
      - IPFS_GATEWAY=true
      - IPFS_API=true
      - IPFS_MIGRATION_ACTIVE=true    
      - IPFS_GATEWAY_SUBDOMAIN=true
      - IPFS_PROFILE=server
      - IPFS_API_HOST=0.0.0.0    # Allow external connections
    volumes:
      - ipfs-data:/data/ipfs
    networks:
      smart_node_ipfs:
        aliases:
          - ipfs
    restart: unless-stopped

networks:
  smart_node_ipfs:
    name: smart_node_ipfs
    driver: bridge

volumes:
    ipfs-data: